---
- hosts: all
  become: yes
  handlers:
  - name: restart opensearch
    service:
      name: opensearch
      state: restarted
  
  - name: restart opensearch dashboards
    service:
      name: opensearch-dashboards
      state: restarted

  tasks:
  - sysctl:
      name: vm.max_map_count
      value: 262144
      sysctl_set: yes
      reload: yes

  - get_url:
      url: https://artifacts.opensearch.org/releases/bundle/opensearch/1.0.1/opensearch-1.0.1-linux-x64.tar.gz
      dest: /tmp/opensearch-1.0.1-linux-x64.tar.gz

  - get_url:
      url: https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/1.0.1/opensearch-dashboards-1.0.1-linux-x64.tar.gz
      dest: /tmp/opensearch-dashboards-1.0.1-linux-x64.tar.gz

  - group:
     name: opensearch

  - user:
      name: opensearch
      group: opensearch

  - file:
      path: /opt/opensearch-1.0.1
      state: directory
      owner: opensearch
      group: opensearch

  - file:
      path: /opt/opensearch-dashboards-1.0.1
      state: directory
      owner: opensearch
      group: opensearch
  
  # TODO: Get rid of strip-components arg
  - unarchive:
      src: /tmp/opensearch-1.0.1-linux-x64.tar.gz
      dest: /opt/opensearch-1.0.1
      owner: opensearch
      group: opensearch
      remote_src: yes
      extra_opts:
      - --strip-components=1

  - unarchive:
      src: /tmp/opensearch-dashboards-1.0.1-linux-x64.tar.gz
      dest: /opt/opensearch-dashboards-1.0.1
      owner: opensearch
      group: opensearch
      remote_src: yes
      extra_opts:
      - --strip-components=1

  - template:
      src: dashboards-config.yml.j2
      dest: /opt/opensearch-dashboards-1.0.1/config/opensearch_dashboards.yml
      owner: opensearch
      group: opensearch
    notify:
    - restart opensearch dashboards
    tags:
    - dev
  
  - template:
      src: opensearch-config.yml.j2
      dest: /opt/opensearch-1.0.1/config/opensearch.yml
      owner: opensearch
      group: opensearch
    notify:
    - restart opensearch
    tags:
    - dev

  - template:
      src: opensearch.service.j2
      dest: /etc/systemd/system/opensearch.service
    tags:
    - dev

  # TODO: fix autostart on reboot
  - systemd:
      state: started
      enabled: yes
      name: opensearch
      daemon_reload: yes
    tags:
    - dev

  - template:
      src: opensearch-dashboards.service.j2
      dest: /etc/systemd/system/opensearch-dashboards.service
    tags:
    - dev

  - systemd:
      state: started
      enabled: yes
      name: opensearch-dashboards
      daemon_reload: yes
    tags:
    - dev