opensearch_listen_ip: "{{ ansible_default_ipv4.address }}"
opensearch_address: "https://{{ opensearch_listen_ip }}:9200"

opensearch_discovery_seed_hosts: "{{ groups['opensearch'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
opensearch_cluster_initial_master_nodes:
- "{{ hostvars[ groups['opensearch'][0] ].ansible_hostname }}"