---
driver:
  name: docker

lint: |
  set -e
  yamllint .
  flake8
  ansible-lint

platforms:
- name: elastic
  image: ubuntu:20.04
  command: /usr/sbin/init
  privileged: True
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  groups:
  - opensearch

provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml

scenario:
  name: default
