---
- name: Increase vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_set: yes
    reload: yes

- name: Check if Opensearch is installed
  stat:
    path: "{{ opensearch_install_dir }}/opensearch-tar-install.sh"
  register: stat_result

- name: Download Opensearch package
  get_url:
    url: "{{ opensearch_download_url }}"
    dest: "/tmp/{{ opensearch_archive_filename }}"
  when: not stat_result.stat.exists

- name: Create group for Opensearch
  group:
    name: "{{ opensearch_group }}"

- name: Create user for Opensearch
  user:
    name: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"

- name: Create directory for Opensearch
  file:
    path: "{{ opensearch_install_dir }}"
    state: directory
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"

# TODO: Get rid of strip-components arg
- name: Unarchive Opensearch package to install dir
  unarchive:
    src: "/tmp/{{ opensearch_archive_filename }}"
    dest: "{{ opensearch_install_dir }}"
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    creates: "{{ opensearch_install_dir }}/opensearch-tar-install.sh"
    remote_src: yes
    extra_opts:
    - --strip-components=1

# Quick fix to generate demo certificates
- name: Create Demo certificates
  shell:
    cmd: sudo -u opensearch bash ./plugins/opensearch-security/tools/install_demo_configuration.sh -y
    chdir: "{{ opensearch_install_dir }}"
    creates: "{{ opensearch_install_dir }}/config/esnode.pem"

- name: Configure Opensearch
  template:
    src: opensearch-config.yml.j2
    dest: "{{ opensearch_install_dir }}/config/opensearch.yml"
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
  notify:
  - restart opensearch

- name: Create systemd service for Opensearch
  template:
    src: opensearch.service.j2
    dest: /etc/systemd/system/opensearch.service

- name: Run Opensearch
  systemd:
    state: started
    enabled: yes
    name: opensearch
    daemon_reload: yes
