---
- sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_set: yes
    reload: yes

- get_url:
    url: https://artifacts.opensearch.org/releases/bundle/opensearch/1.0.1/opensearch-1.0.1-linux-x64.tar.gz
    dest: /tmp/opensearch-1.0.1-linux-x64.tar.gz

- group:
    name: opensearch

- user:
    name: opensearch
    group: opensearch

- file:
    path: /opt/opensearch-1.0.1
    state: directory
    owner: opensearch
    group: opensearch

# TODO: Get rid of strip-components arg
- unarchive:
    src: /tmp/opensearch-1.0.1-linux-x64.tar.gz
    dest: /opt/opensearch-1.0.1
    owner: opensearch
    group: opensearch
    remote_src: yes
    extra_opts:
    - --strip-components=1

# Quick fix to generate demo certificates
- shell:
    cmd: sudo -u opensearch bash ./plugins/opensearch-security/tools/install_demo_configuration.sh -y
    chdir: /opt/opensearch-1.0.1
    creates: /opt/opensearch-1.0.1/config/esnode.pem

- template:
    src: opensearch-config.yml.j2
    dest: /opt/opensearch-1.0.1/config/opensearch.yml
    owner: opensearch
    group: opensearch
  notify:
  - restart opensearch

- template:
    src: opensearch.service.j2
    dest: /etc/systemd/system/opensearch.service

- systemd:
    state: started
    enabled: yes
    name: opensearch
    daemon_reload: yes
